<a href="https://colab.research.google.com/github/Mgolombane/Loki/blob/main/Loki.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
x = 1
print(x)

1


In [8]:
import tensorflow as tf
string = tf.Variable("this is a string", tf.string)
number = tf.Variable(324, tf.int16)
floating = tf.Variable(3.567, tf.float64)

print(string)

rank1_tensor = tf.Variable(["Test", "ok", "Tin"], tf.string)
rank2_tensor = tf.Variable([["test", "ok"], ["test", "yes"]], tf.string)

print(tf.rank(rank1_tensor))

print(tf.rank(rank2_tensor))

rank2_tensor.shape

rank1_tensor.shape

tensor1 = tf.ones([1,2,3]) # tf.ones() creates a shape [1,2,3] tensor full of ones

tensor2 = tf.reshape(tensor1, [2,3,1]) #reshape existing data to shape [2,3,1]

tensor3 = tf.reshape(tensor2, [3, -1])  # -1 tells the tensor to calculate the size of the dimension in that place

                                        #this will reshape the tensor to [3,2]

# the number of elements in the reshaped tensor MUST match the numbe in the original


print(tensor1)
print(tensor2)
print(tensor3)

# Notice the changes in shape

#Check the tensorflow website - https://www.tensorflow.org/guide/tensor




<tf.Variable 'Variable:0' shape=() dtype=string, numpy=b'this is a string'>
tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(
[[[1. 1. 1.]
  [1. 1. 1.]]], shape=(1, 2, 3), dtype=float32)
tf.Tensor(
[[[1.]
  [1.]
  [1.]]

 [[1.]
  [1.]
  [1.]]], shape=(2, 3, 1), dtype=float32)
tf.Tensor(
[[1. 1.]
 [1. 1.]
 [1. 1.]], shape=(3, 2), dtype=float32)
